name: Crawl SwedishFind

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/crawl-swedishfind.yml
      - swedishfind/crawler/**
  schedule:
    - cron: "25,55 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    name: Crawl SwedishFind
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'swedishfind/package-lock.json'
          
      - name: Crawl SwedishFind
        run: |
          cd swedishfind
          npm ci
          npm run crawlLocations
          npm run crawlClasses

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/swedishfind-update
          delete-branch: true
          title: "chore: update swedishfind generated files"
          commit-message: "chore: update swedishfind generated files"
          body: "Automated update generated by GitHub Actions."
          labels: automated
